import { fileURLToPath } from 'node:url';

import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';

import * as schema from './schema/index.js';

export interface CreateDbOptions {
  /**
   * Postgres URL, parsed by the app with `parseEnv()` from @asc/config
   * (`DATABASE_URL`). This package never reads `process.env`. Deployed
   * environments must use TLS (`?sslmode=require`).
   */
  url: string;
  /** Max pool connections (default 10). */
  max?: number;
}

export function createDb({ url, max = 10 }: CreateDbOptions) {
  // postgres.js logs server notices with console.log by default; drop them (no console in app code).
  const client = postgres(url, { max, onnotice: () => {} });
  const db = drizzle(client, { schema });
  return {
    db,
    /** Drains the pool. Call on shutdown. */
    close: () => client.end({ timeout: 5 }),
  };
}

export type Db = ReturnType<typeof createDb>['db'];

/**
 * SQL migrations generated by drizzle-kit (`pnpm db:generate`). Resolved from
 * this source file, so valid when run from the repo (tests, tooling) — not from
 * a tsup-bundled app, which should run `pnpm db:migrate` as a deploy step.
 */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../drizzle', import.meta.url));

/** Applies pending migrations (tests, scripts). `pnpm db:migrate` does the same via drizzle-kit. */
export async function runMigrations(db: Db, options: { migrationsSchema?: string } = {}): Promise<void> {
  await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER, migrationsSchema: options.migrationsSchema });
}
