/**
 * Owner-side database access: migrations and tooling only. Entry point
 * `@asc/db/migrate`, deliberately NOT re-exported from `@asc/db`: this client
 * carries no tenant context, and with FORCE row-level security it sees no
 * tenant rows unless a superuser. App code uses `createTenantDb` instead.
 */

import { fileURLToPath } from 'node:url';

import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';

import * as schema from './schema/index.js';

export interface CreateMigrationDbOptions {
  /**
   * OWNER Postgres URL (`DATABASE_URL` from `parseEnv()` in @asc/config), never
   * the runtime URL. This package never reads `process.env`. Deployed
   * environments must use TLS (`?sslmode=require`).
   */
  url: string;
  /**
   * The configured tenant (`DEFAULT_TENANT_ID`). Passed to the session as
   * `app.default_tenant_id` so the backfill migration can adopt rows written
   * before tenancy. Without it, such rows stop the migration.
   */
  defaultTenantId?: string;
  /** Max pool connections (default 2). */
  max?: number;
}

export function createMigrationDb({ url, defaultTenantId, max = 2 }: CreateMigrationDbOptions) {
  // postgres.js logs server notices with console.log by default; drop them (no console in app code).
  const client = postgres(url, {
    max,
    onnotice: () => {},
    connection: defaultTenantId ? { 'app.default_tenant_id': defaultTenantId } : {},
  });
  const db = drizzle(client, { schema });
  return {
    db,
    /** Drains the pool. */
    close: () => client.end({ timeout: 5 }),
  };
}

export type Db = ReturnType<typeof createMigrationDb>['db'];

/**
 * SQL migrations generated by drizzle-kit (`pnpm db:generate`). Resolved from
 * this source file, so valid when run from the repo (tests, tooling) — not from
 * a tsup-bundled app, which should run `pnpm db:migrate` as a deploy step.
 */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../drizzle', import.meta.url));

/** Applies pending migrations (tests, scripts). `pnpm db:migrate` does the same via drizzle-kit. */
export async function runMigrations(db: Db, options: { migrationsSchema?: string } = {}): Promise<void> {
  await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER, migrationsSchema: options.migrationsSchema });
}
