// Primitives (shadcn on Base UI)
export * from "./components/ui/avatar";
export * from "./components/ui/badge";
export * from "./components/ui/button";
export * from "./components/ui/card";
export * from "./components/ui/checkbox";
export * from "./components/ui/dialog";
export * from "./components/ui/dropdown-menu";
export * from "./components/ui/input";
export * from "./components/ui/kbd";
export * from "./components/ui/label";
export * from "./components/ui/progress";
export * from "./components/ui/select";
export * from "./components/ui/separator";
export * from "./components/ui/sheet";
export * from "./components/ui/sidebar";
export * from "./components/ui/skeleton";
export * from "./components/ui/sonner";
export * from "./components/ui/switch";
export * from "./components/ui/table";
export * from "./components/ui/tabs";
export * from "./components/ui/textarea";
export * from "./components/ui/tooltip";
export * from "./lib/utils";

// Forms, theme, navigation
export * from "./components/form/form-field";
export * from "./components/navigation/command-palette";
export * from "./components/theme/theme-provider";
export * from "./components/theme/theme-toggle";

// Clinical kit (presentational: props in, callbacks out) — see CATALOG.md
export * from "./components/clinical/ai-badge";
export * from "./components/clinical/data-table";
export * from "./components/clinical/draft-banner";
export * from "./components/clinical/empty-state";
export * from "./components/clinical/error-state";
export * from "./components/clinical/gap-chip";
export * from "./components/clinical/gate-checklist";
export * from "./components/clinical/loading-skeleton";
export * from "./components/clinical/page-header";
export * from "./components/clinical/patient-banner";
export * from "./components/clinical/phase-chip";
export * from "./components/clinical/phase-stepper";
export * from "./components/clinical/phase-style";
export * from "./components/clinical/provenance-chip";
export * from "./components/clinical/section-card";
export * from "./components/clinical/stat-card";
export * from "./components/clinical/timeline";
