import type { RoleTemplate } from "@asc/types";
import { REFERENCE_READ, ro, rw } from "./rules.js";

export const giPhysician: RoleTemplate = {
  key: "gi-physician",
  version: 1,
  label: "GI physician",
  status: "active",
  capabilities: [
    "patient.read",
    "schedule.read",
    "whiteboard.read",
    "case.read",
    "case.advance",
    "hp.document",
    "medhold.review",
    "consent.collect",
    "procedure.document",
    "specimen.manage",
    "note.draft",
    "note.edit",
    "note.sign",
    "discharge.approve",
    "coding.review",
    "pathology.reconcile",
    "breakglass.invoke",
    "consent.witness",
    "timeout.participate",
    "image.manage",
    "note.addend",
    "referral.triage",
    "pathology.letter.send",
    "ai.generate",
    "case.cancel",
  ],
  data: [
    ro("Patient"),
    ro("Coverage"),
    ro("Appointment"),
    rw("Encounter"),
    rw("QuestionnaireResponse"),
    // A signed (`final`) procedure note can never be overwritten.
    { resourceType: "Composition", lockWhenFinal: true },
    ro("MedicationAdministration"),
    ro("Observation"),
    ro("ChargeItem"),
    ...REFERENCE_READ,
    rw("Task"),
    rw("Consent"),
    rw("Procedure"),
    rw("Specimen"),
    rw("DiagnosticReport"),
    rw("DocumentReference"),
    rw("ServiceRequest"),
  ],
  facilityScoped: true,
  requiresMfa: true,
};
